### ISSUE TITLE
Change packages to new Civcraft domain name

### ISSUE THREAD

**Issue by rourke750** [gmlaxfanatic/Contraptions#24]
instead of com.untamdears change to vg.civcraft.mc

**Comment by WildWeazel** [comment]
Are we planning to standardize everything to one package scheme?

**Comment by rourke750** [comment]
I think it would be a good idea.  Its a way to uniquely identify all the plugins that come from Civcraft Development.

**Comment by gmlaxfanatic** [comment]
Fixed by 39f9ac2b90
