### ISSUE TITLE
I broke my finger...

### ISSUE THREAD

**Issue by gmlaxfanatic** [gmlaxfanatic/Contraptions#32]
Probably 2-6 weeks before I can start coding again... :(

**Comment by ProgrammerDan** [comment]
Oh damn, sorry to hear! Rest up, and I hope the finger knits properly..

**Comment by WildWeazel** [comment]
coding continues at https://github.com/Bergecraft/Contraptions

**Comment by gmlaxfanatic** [comment]
Nice! Hit me up if you have questions. Warning, the different gadgets were still getting thought out, so you might want to rework them. But I was really likely the overall structure of code, especially compared to factorymod.....

**Comment by MonsWTF** [comment]
Oh damn...sorry about the broken finger, man. I didn't realize this was what happened. Hope the recovery went well without complication.
